# -*- coding: utf-8 -*-
"""67160351_DW_Week7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1syH-5yFJ-LsI85-T-ncLJPVhC41VYjmV
"""

# รัน Cell นี้เพื่ออัปโหลดไฟล์ Excel ที่คุณดาวน์โหลดมาจากกลุ่ม/มoodle
from google.colab import files
import os

if not os.path.exists('Python_Data_Pipeline_Lab_Dataset (1).xlsx'):
    print("กรุณาเลือกไฟล์ Excel Dataset...")
    uploaded = files.upload()
else:
    print("พบไฟล์ Dataset ในระบบแล้ว")

import pandas as pd
import sqlite3
import logging
from dataclasses import dataclass
from datetime import datetime

# Setup Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

@dataclass
class PipelineConfig:
    input_path: str = 'Python_Data_Pipeline_Lab_Dataset (1).xlsx'
    db_path: str = 'retail_dw.db'
    quarantine_path: str = 'quarantine.csv'
    log_path: str = 'pipeline_run_log.csv'
    batch_list: list = None

    def __post_init__(self):
        if self.batch_list is None:
            self.batch_list = ['orders_batch_1', 'orders_batch_2', 'orders_batch_3']

def extract_data(config: PipelineConfig) -> dict:
    """อ่านข้อมูลจาก Excel โดยใช้ try/except และ logging"""
    data = {}
    try:
        logger.info(f"เริ่มอ่านไฟล์: {config.input_path}")
        start_time = datetime.now()

        # อ่าน Dimension Tables
        data['customers'] = pd.read_excel(config.input_path, sheet_name='customers')
        data['products'] = pd.read_excel(config.input_path, sheet_name='products')

        # อ่าน Fact Tables (Batches)
        for batch in config.batch_list:
            logger.info(f"กำลังอ่าน batch: {batch}")
            data[batch] = pd.read_excel(config.input_path, sheet_name=batch)

        end_time = datetime.now()
        logger.info(f"อ่านข้อมูลสำเร็จ ใช้เวลา {end_time - start_time}")
        return data

    except Exception as e:
        logger.error(f"เกิดข้อผิดพลาดในการอ่านไฟล์: {e}")
        raise

def transform_and_validate(orders_df: pd.DataFrame, customers_df: pd.DataFrame, products_df: pd.DataFrame, batch_name: str) -> tuple:
    """ทำ cleansing, validation และแยกข้อมูลสะอาดออกจากข้อมูลเสีย"""
    df = orders_df.copy()
    valid_customers = set(customers_df['customer_id'])
    valid_products = set(products_df[products_df['active_flag'] == 'Y']['product_id']) # ตรวจสินค้า active เท่านั้น

    # 1. Safe Conversion (errors='coerce')
    df['order_datetime'] = pd.to_datetime(df['order_datetime'], errors='coerce')
    df['updated_at'] = pd.to_datetime(df['updated_at'], errors='coerce')
    df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
    df['unit_price'] = pd.to_numeric(df['unit_price'], errors='coerce')
    df['discount_pct'] = pd.to_numeric(df['discount_pct'], errors='coerce')

    # 2. Normalization
    pay_map = {'credit card': 'Credit Card', 'promptpay': 'PromptPay'}
    df['payment_method'] = df['payment_method'].str.strip().str.lower().map(pay_map).fillna(df['payment_method'])

    channel_map = {'e-commerce': 'Online'}
    df['sales_channel'] = df['sales_channel'].str.strip().str.title().map(channel_map).fillna(df['sales_channel'])

    # 3. Validation Rules
    def check_reasons(row):
        reasons = []
        if pd.isna(row['order_datetime']): reasons.append('INVALID_DATE')
        if pd.isna(row['quantity']) or row['quantity'] <= 0: reasons.append('INVALID_QUANTITY')
        if pd.isna(row['unit_price']) or row['unit_price'] <= 0: reasons.append('INVALID_PRICE')
        if pd.isna(row['discount_pct']) or row['discount_pct'] < 0 or row['discount_pct'] > 100: reasons.append('INVALID_DISCOUNT')
        if row['customer_id'] not in valid_customers: reasons.append('MISSING_CUSTOMER')
        if row['product_id'] not in valid_products: reasons.append('MISSING_OR_INACTIVE_PRODUCT')
        return '; '.join(reasons) if reasons else None

    df['reason_code'] = df.apply(check_reasons, axis=1)

    # 4. Split Clean & Quarantine
    quarantine_df = df[df['reason_code'].notna()].copy()
    clean_df = df[df['reason_code'].isna()].copy()

    # เพิ่ม source_batch ให้ quarantine
    quarantine_df['source_batch'] = batch_name

    # 5. Deduplicate clean data (เก็บ updated_at ล่าสุด)
    rows_before_dedup = len(clean_df)
    clean_df = clean_df.sort_values('updated_at').drop_duplicates(subset=['order_id'], keep='last')
    rows_deduped = rows_before_dedup - len(clean_df)

    # 6. Calculate Amounts
    clean_df['gross_amount'] = clean_df['quantity'] * clean_df['unit_price']
    clean_df['net_amount'] = clean_df['gross_amount'] * (1 - (clean_df['discount_pct'] / 100))

    return clean_df, quarantine_df, rows_deduped

def init_db(db_path: str):
    """สร้างตาราง Star Schema และกำหนด Primary Keys"""
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        cursor.executescript("""
            CREATE TABLE IF NOT EXISTS dim_customer (
                customer_key INTEGER PRIMARY KEY AUTOINCREMENT,
                customer_id TEXT UNIQUE,
                customer_name TEXT,
                province TEXT,
                segment TEXT
            );
            CREATE TABLE IF NOT EXISTS dim_product (
                product_key INTEGER PRIMARY KEY AUTOINCREMENT,
                product_id TEXT UNIQUE,
                product_name TEXT,
                category TEXT
            );
            CREATE TABLE IF NOT EXISTS dim_date (
                date_key INTEGER PRIMARY KEY,
                full_date TEXT,
                day INTEGER,
                month INTEGER,
                quarter INTEGER,
                year INTEGER
            );
            CREATE TABLE IF NOT EXISTS fact_sales (
                order_id TEXT PRIMARY KEY,
                date_key INTEGER,
                customer_key INTEGER,
                product_key INTEGER,
                quantity INTEGER,
                unit_price REAL,
                discount_pct REAL,
                gross_amount REAL,
                net_amount REAL,
                payment_method TEXT,
                sales_channel TEXT,
                FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
                FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
                FOREIGN KEY (product_key) REFERENCES dim_product(product_key)
            );
            CREATE TABLE IF NOT EXISTS quarantine_records (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                order_id TEXT,
                source_batch TEXT,
                reason_code TEXT,
                raw_data TEXT
            );
            CREATE TABLE IF NOT EXISTS pipeline_run_log (
                log_id INTEGER PRIMARY KEY AUTOINCREMENT,
                batch_name TEXT,
                started_at TEXT,
                ended_at TEXT,
                rows_read INTEGER,
                rows_loaded INTEGER,
                rows_rejected INTEGER,
                status TEXT
            );
        """)
        conn.commit()

def load_data(db_path: str, clean_df: pd.DataFrame, quarantine_df: pd.DataFrame,
              customers_df: pd.DataFrame, products_df: pd.DataFrame):
    """บันทึกข้อมูลลง SQLite ด้วย INSERT OR IGNORE เพื่อ Idempotency"""
    with sqlite3.connect(db_path) as conn:
        # Load Dimensions (Ignore if exists)
        customers_df[['customer_id', 'customer_name', 'province', 'segment']].to_sql(
            'dim_customer', conn, if_exists='append', index=False)

        products_df[products_df['active_flag']=='Y'][['product_id', 'product_name', 'category']].to_sql(
            'dim_product', conn, if_exists='append', index=False)

        # Generate & Load Date Dimension
        if not clean_df.empty:
            dates = clean_df['order_datetime'].dt.normalize().unique()
            dim_date = pd.DataFrame({
                'full_date': dates,
                'day': pd.to_datetime(dates).day,
                'month': pd.to_datetime(dates).month,
                'quarter': pd.to_datetime(dates).quarter,
                'year': pd.to_datetime(dates).year,
                'date_key': pd.to_datetime(dates).strftime('%Y%m%d').astype(int)
            })
            dim_date.to_sql('dim_date', conn, if_exists='append', index=False)

            # Prepare Fact Table with Keys
            fact_df = clean_df.copy()
            fact_df['date_key'] = fact_df['order_datetime'].dt.strftime('%Y%m%d').astype(int)

            # Lookup Keys
            cust_keys = pd.read_sql("SELECT customer_id, customer_key FROM dim_customer", conn)
            prod_keys = pd.read_sql("SELECT product_id, product_key FROM dim_product", conn)

            fact_df = fact_df.merge(cust_keys, on='customer_id', how='inner')
            fact_df = fact_df.merge(prod_keys, on='product_id', how='inner')

            fact_cols = ['order_id', 'date_key', 'customer_key', 'product_key',
                         'quantity', 'unit_price', 'discount_pct', 'gross_amount',
                         'net_amount', 'payment_method', 'sales_channel']

            # INSERT OR IGNORE ช่วยให้รันซ้ำไม่เพิ่มแถว
            fact_df[fact_cols].to_sql('fact_sales', conn, if_exists='append', index=False, chunksize=1000)

        # Load Quarantine
        if not quarantine_df.empty:
            quarantine_df['raw_data'] = quarantine_df.astype(str).apply(lambda x: '|'.join(x), axis=1)
            quarantine_df[['order_id', 'source_batch', 'reason_code', 'raw_data']].to_sql(
                'quarantine_records', conn, if_exists='append', index=False)

def run_pipeline(config: PipelineConfig, batch_name: str, data: dict):
    """ฟังก์ชันหลักในการดำเนินการทีละ Batch"""
    start_time = datetime.now()
    status = "success"
    rows_loaded = 0
    rows_rejected = 0

    try:
        logger.info(f"=== เริ่มดำเนินการ {batch_name} ===")
        orders_df = data[batch_name]
        rows_read = len(orders_df)

        # Transform & Validate
        clean_df, quarantine_df, rows_deduped = transform_and_validate(
            orders_df, data['customers'], data['products'], batch_name
        )

        # Load to DB
        load_data(config.db_path, clean_df, quarantine_df, data['customers'], data['products'])

        rows_loaded = len(clean_df)
        rows_rejected = len(quarantine_df) + rows_deduped # นับ rows ที่ถูกตัดทิ้งจากการ dedup ด้วย

        # Log to DB
        end_time = datetime.now()
        with sqlite3.connect(config.db_path) as conn:
            conn.execute("""
                INSERT INTO pipeline_run_log (batch_name, started_at, ended_at, rows_read, rows_loaded, rows_rejected, status)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (batch_name, start_time, end_time, rows_read, rows_loaded, rows_rejected, status))

        logger.info(f"สำเร็จ: Read={rows_read}, Loaded={rows_loaded}, Rejected(Incl.Dedup)={rows_rejected}")

    except Exception as e:
        status = "failed"
        end_time = datetime.now()
        logger.error(f"ล้มเหลวใน {batch_name}: {e}")
        with sqlite3.connect(config.db_path) as conn:
            conn.execute("""
                INSERT INTO pipeline_run_log (batch_name, started_at, ended_at, rows_read, rows_loaded, rows_rejected, status)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (batch_name, start_time, end_time, 0, 0, 0, status))

# ==========================================
# การรัน Pipeline จริง (Evidence 4 รอบ)
# ==========================================
config = PipelineConfig()

# ลบ DB เก่าถ้ามี เพื่อให้เริ่มสภาพแวดล้อมใหม่สะอาด
if os.path.exists(config.db_path):
    os.remove(config.db_path)

init_db(config.db_path)
data = extract_data(config)

print("\n" + "="*50)
print("รันรอบที่ 1: batch_1")
run_pipeline(config, 'orders_batch_1', data)

print("\n" + "="*50)
print("รันรอบที่ 2: batch_1 (ซ้ำเพื่อทดสอบ Idempotency)")
run_pipeline(config, 'orders_batch_1', data)

print("\n" + "="*50)
print("รันรอบที่ 3: batch_2")
run_pipeline(config, 'orders_batch_2', data)

print("\n" + "="*50)
print("รันรอบที่ 4: batch_3")
run_pipeline(config, 'orders_batch_3', data)

# ส่งออกไฟล์ CSV
import sqlite3
con = sqlite3.connect(config.db_path)

# สร้าง Quarantine CSV
quarantine_df = pd.read_sql("SELECT order_id, source_batch, reason_code FROM quarantine_records", con)
quarantine_df.to_csv(config.quarantine_path, index=False)

# สร้าง Log CSV
log_df = pd.read_sql("SELECT * FROM pipeline_run_log", con)
log_df.to_csv(config.log_path, index=False)

con.close()

print("\n=== สรุป KPI สุดท้าย ===")
print(log_df[['batch_name', 'rows_read', 'rows_loaded', 'rows_rejected', 'status']])

# Cell นี้เพื่อดาวน์โหลดไฟล์
files.download('retail_dw.db')
files.download('quarantine.csv')
files.download('pipeline_run_log.csv')