# -*- coding: utf-8 -*-
"""67160351 Data warehouse retail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FShU_klsLzkrZz2n5F2ZgrkuMyZeO6C
"""

# อัปโหลดไฟล์ retail_logs.csv เข้า Colab ก่อน หรือสร้างจากข้อมูลด้านบน
# ตรวจสอบไฟล์
import os
print(os.listdir())

# Commented out IPython magic to ensure Python compatibility.
# %%writefile etl_pipeline.py
# """
# ETL Pipeline: retail_logs.csv -> Star Schema (SQLite)
# - 1 Fact Table : fact_sales
# - 3 Dimension  : dim_location, dim_product, dim_date
# - Output       : retail_warehouse.db
# """
# from __future__ import annotations
# import re
# import sqlite3
# import pandas as pd
# 
# DATA_PATH   = "retail_logs.csv"
# DB_PATH     = "retail_warehouse.db"
# 
# # ---------- Helper functions ----------
# def clean_text(value, default="Unknown") -> str:
#     if pd.isna(value) or str(value).strip() == "":
#         return default
#     return " ".join(str(value).strip().split()).title()
# 
# def clean_number(value) -> float | None:
#     if pd.isna(value) or str(value).strip() == "":
#         return None
#     cleaned = re.sub(r"[^0-9.\-]", "", str(value))
#     return float(cleaned) if cleaned else None
# 
# def parse_mixed_date(value) -> pd.Timestamp:
#     text = "" if pd.isna(value) else str(value).strip()
#     for fmt in ["%Y-%m-%d", "%d-%b-%Y", "%d/%m/%Y", "%d-%m-%Y"]:
#         try:
#             return pd.to_datetime(text, format=fmt, errors="raise")
#         except Exception:
#             continue
#     return pd.to_datetime(text, errors="coerce", dayfirst=True)
# 
# # ---------- EXTRACT ----------
# def extract() -> pd.DataFrame:
#     df = pd.read_csv(DATA_PATH, dtype=str, encoding="utf-8-sig")
#     df.columns = [c.strip().lower() for c in df.columns]
#     # จัดการชื่อคอลัมน์ที่อาจมี BOM
#     df = df.rename(columns={"\ufeffsale_id": "sale_id"})
#     print(f"[Extract] raw rows={len(df):,}  | duplicate sale_id={df.duplicated('sale_id').sum():,}")
#     return df
# 
# # ---------- TRANSFORM ----------
# def transform(df: pd.DataFrame):
#     df = df.drop_duplicates(subset=["sale_id"], keep="first").copy()
# 
#     # --- Clean fields ---
#     df["branch"]   = df["branch"].apply(clean_text)
#     df["province"] = df["province"].apply(clean_text)
#     df["region"]   = df["region"].apply(lambda v: clean_text(v, "Unknown"))
#     df["product_name"] = df["product_name"].apply(clean_text)
#     df["category"]     = df["category"].apply(lambda v: clean_text(v, "Unknown"))
#     df["sale_date"]    = df["sale_date"].apply(parse_mixed_date)
#     df["quantity"]   = pd.to_numeric(df["quantity"].apply(clean_number), errors="coerce").fillna(0).astype(int)
#     df["unit_price"] = df["unit_price"].apply(clean_number)
#     df["discount_percent"] = df["discount_percent"].apply(clean_number).fillna(0)
# 
#     df = df.dropna(subset=["sale_date", "unit_price"]).copy()
#     df = df[(df["quantity"] > 0) & (df["unit_price"] >= 0)].copy()
#     df["discount_percent"] = df["discount_percent"].clip(0, 100)
# 
#     # total_amount = qty * price * (1 - discount/100)
#     df["total_amount"] = (df["quantity"] * df["unit_price"] * (1 - df["discount_percent"]/100)).round(2)
# 
#     # --- Build dim_location ---
#     dim_location = (
#         df[["store_code", "branch", "province", "region"]]
#         .drop_duplicates()
#         .sort_values(["region", "province", "branch"])
#         .reset_index(drop=True)
#     )
#     dim_location.insert(0, "location_id", range(1, len(dim_location) + 1))
# 
#     # --- Build dim_product ---
#     dim_product = (
#         df[["product_name", "category"]]
#         .drop_duplicates()
#         .sort_values(["category", "product_name"])
#         .reset_index(drop=True)
#     )
#     dim_product.insert(0, "product_id", range(1, len(dim_product) + 1))
# 
#     # --- Build dim_date ---
#     dim_date = df[["sale_date"]].drop_duplicates().sort_values("sale_date").reset_index(drop=True)
#     dim_date = dim_date.rename(columns={"sale_date": "full_date"})
#     dim_date["date_id"]    = dim_date["full_date"].dt.strftime("%Y%m%d").astype(int)
#     dim_date["day"]        = dim_date["full_date"].dt.day
#     dim_date["month"]      = dim_date["full_date"].dt.month
#     dim_date["month_name"] = dim_date["full_date"].dt.month_name()
#     dim_date["quarter"]    = "Q" + dim_date["full_date"].dt.quarter.astype(str)
#     dim_date["year"]       = dim_date["full_date"].dt.year
#     dim_date["weekday"]    = dim_date["full_date"].dt.day_name()
#     dim_date = dim_date[["date_id", "full_date", "day", "month", "month_name", "quarter", "year", "weekday"]]
# 
#     # --- Build fact_sales (map FK) ---
#     mapped = df.merge(dim_location, on=["store_code", "branch", "province", "region"], how="left", validate="many_to_one")
#     mapped = mapped.merge(dim_product, on=["product_name", "category"], how="left", validate="many_to_one")
#     mapped = mapped.merge(dim_date, left_on="sale_date", right_on="full_date", how="left", validate="many_to_one")
# 
#     fact_sales = mapped[[
#         "sale_id", "location_id", "product_id", "date_id",
#         "quantity", "unit_price", "discount_percent", "total_amount"
#     ]].rename(columns={"sale_id": "transaction_id"})
#     fact_sales[["location_id", "product_id", "date_id"]] = fact_sales[["location_id", "product_id", "date_id"]].astype(int)
# 
#     print(f"[Transform] locations={len(dim_location)} | products={len(dim_product)} | "
#           f"dates={len(dim_date)} | facts={len(fact_sales)}")
#     return dim_location, dim_product, dim_date, fact_sales
# 
# # ---------- LOAD ----------
# def load(dim_location, dim_product, dim_date, fact_sales):
#     with sqlite3.connect(DB_PATH) as conn:
#         conn.execute("PRAGMA foreign_keys = ON;")
#         conn.executescript("""
#         DROP TABLE IF EXISTS fact_sales;
#         DROP TABLE IF EXISTS dim_location;
#         DROP TABLE IF EXISTS dim_product;
#         DROP TABLE IF EXISTS dim_date;
# 
#         CREATE TABLE dim_location (
#             location_id INTEGER PRIMARY KEY,
#             store_code  TEXT NOT NULL,
#             branch      TEXT NOT NULL,
#             province    TEXT NOT NULL,
#             region      TEXT NOT NULL,
#             UNIQUE(store_code, branch, province, region)
#         );
#         CREATE TABLE dim_product (
#             product_id   INTEGER PRIMARY KEY,
#             product_name TEXT NOT NULL,
#             category     TEXT NOT NULL,
#             UNIQUE(product_name, category)
#         );
#         CREATE TABLE dim_date (
#             date_id    INTEGER PRIMARY KEY,
#             full_date  TEXT NOT NULL UNIQUE,
#             day        INTEGER NOT NULL,
#             month      INTEGER NOT NULL,
#             month_name TEXT NOT NULL,
#             quarter    TEXT NOT NULL,
#             year       INTEGER NOT NULL,
#             weekday    TEXT NOT NULL
#         );
#         CREATE TABLE fact_sales (
#             transaction_id   TEXT PRIMARY KEY,
#             location_id      INTEGER NOT NULL REFERENCES dim_location(location_id),
#             product_id       INTEGER NOT NULL REFERENCES dim_product(product_id),
#             date_id          INTEGER NOT NULL REFERENCES dim_date(date_id),
#             quantity         INTEGER NOT NULL CHECK(quantity > 0),
#             unit_price       REAL    NOT NULL CHECK(unit_price >= 0),
#             discount_percent REAL    NOT NULL CHECK(discount_percent BETWEEN 0 AND 100),
#             total_amount     REAL    NOT NULL CHECK(total_amount >= 0)
#         );
#         """)
#         dim_location.to_sql("dim_location", conn, if_exists="append", index=False)
#         dim_product.to_sql("dim_product",  conn, if_exists="append", index=False)
#         dim_date.to_sql("dim_date",        conn, if_exists="append", index=False)
#         fact_sales.to_sql("fact_sales",    conn, if_exists="append", index=False)
#         conn.commit()
#     print(f"[Load] database saved -> {DB_PATH}")
# 
# # ---------- VERIFY ----------
# def verify():
#     queries = {
#         "Row counts": """
#             SELECT 'dim_location' AS tbl, COUNT(*) AS n FROM dim_location
#             UNION ALL SELECT 'dim_product', COUNT(*) FROM dim_product
#             UNION ALL SELECT 'dim_date',    COUNT(*) FROM dim_date
#             UNION ALL SELECT 'fact_sales',  COUNT(*) FROM fact_sales;
#         """,
#         "Top 5 Products by Revenue": """
#             SELECT p.product_name, p.category,
#                    SUM(f.quantity) AS qty,
#                    ROUND(SUM(f.total_amount), 2) AS revenue
#             FROM fact_sales f
#             JOIN dim_product p ON f.product_id = p.product_id
#             GROUP BY p.product_id, p.product_name, p.category
#             ORDER BY revenue DESC
#             LIMIT 5;
#         """,
#         "Revenue by Region": """
#             SELECT l.region, l.province,
#                    COUNT(*) AS tx,
#                    ROUND(SUM(f.total_amount), 2) AS revenue
#             FROM fact_sales f
#             JOIN dim_location l ON f.location_id = l.location_id
#             GROUP BY l.region, l.province
#             ORDER BY revenue DESC;
#         """,
#         "Monthly Revenue Trend": """
#             SELECT d.year, d.month, d.month_name,
#                    ROUND(SUM(f.total_amount), 2) AS revenue
#             FROM fact_sales f
#             JOIN dim_date d ON f.date_id = d.date_id
#             GROUP BY d.year, d.month, d.month_name
#             ORDER BY d.year, d.month;
#         """
#     }
#     with sqlite3.connect(DB_PATH) as conn:
#         for title, sql in queries.items():
#             print(f"\n=== {title} ===")
#             print(pd.read_sql_query(sql, conn).to_string(index=False))
# 
# # ---------- MAIN ----------
# if __name__ == "__main__":
#     raw = extract()
#     dims_fact = transform(raw)
#     load(*dims_fact)
#     verify()
#     print("\n✅ ETL Pipeline run successfully!")

!python etl_pipeline.py

import sqlite3, pandas as pd
conn = sqlite3.connect("retail_warehouse.db")

# ดู schema ทั้งหมด
print(pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn))

# ดูตัวอย่าง fact_sales
print(pd.read_sql_query("SELECT * FROM fact_sales LIMIT 5;", conn))

conn.close()