# -*- coding: utf-8 -*-
"""Copy of 01_student_lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170JvNzbPtxoowDU8xd0fcXSE1yHbkuH0

# Lab Assignment: Data Quality & Data Cleaning for Data Warehouse

**สถานการณ์:** คุณเป็น Data Engineer ของร้านค้าออนไลน์ และได้รับไฟล์ `e_commerce_raw.csv` ที่ต้องเตรียมก่อนโหลดเข้าสู่ Data Warehouse  
**เป้าหมาย:** สำรวจปัญหาคุณภาพข้อมูล ออกแบบกฎการทำความสะอาด และส่งออกข้อมูลที่พร้อมใช้งาน

> ห้ามลบข้อมูลผิดปกติโดยไม่อธิบายเหตุผล ต้องพิจารณา Business Context โดยเฉพาะรายการโปรโมชัน

## ผลลัพธ์การเรียนรู้
1. ตรวจสอบข้อมูลด้วย `info()`, `isnull()`, `describe()` และ `duplicated()`
2. เชื่อมโยงปัญหากับ 6 มิติ: Accuracy, Completeness, Consistency, Uniqueness, Timeliness, Validity
3. จัดการ Missing Values และรูปแบบข้อมูลที่ไม่สอดคล้อง
4. ตรวจจับ Outlier ด้วย IQR และทำ Capping อย่างมีเหตุผล
5. สร้างไฟล์ Clean Data และรายงาน Data Quality ก่อน–หลัง

## 0) เตรียมระบบและอ่านข้อมูล
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
DATA_PATH = ROOT / 'e_commerce_raw.csv'
OUTPUT_DIR = ROOT / 'outputs' / 'student_submission'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

pd.set_option('display.max_columns', 50)
df_raw = pd.read_csv(DATA_PATH)
df = df_raw.copy()
print('Shape:', df.shape)
df.head()

"""## 1) Data Profiling

ให้แสดงผลต่อไปนี้และเขียนข้อสังเกตใต้เซลล์
- โครงสร้างและชนิดข้อมูล
- จำนวน Missing Values รายคอลัมน์
- สถิติเชิงพรรณนาของข้อมูลตัวเลข
- จำนวนแถวซ้ำทั้งแถว
- จำนวนค่าที่แตกต่างในคอลัมน์สำคัญ

"""

# TODO 1: Data Profiling
# ตัวอย่างคำสั่งที่ควรใช้: df.info(), df.isnull().sum(), df.describe(), df.duplicated().sum()

# TODO 1: Data Profiling
print("="*70)
print("DATA PROFILING REPORT")
print("="*70)

# 1. โครงสร้างและชนิดข้อมูล
print("\n--- 1.1 DataFrame Info ---")
df.info()

# 2. จำนวน Missing Values รายคอลัมน์
print("\n--- 1.2 Missing Values ---")
missing = df.isnull().sum()
missing_pct = (df.isnull().mean() * 100).round(2)
missing_report = pd.DataFrame({
    'Missing_Count': missing,
    'Missing_Percent': missing_pct
})
print(missing_report[missing_report['Missing_Count'] > 0])

# 3. สถิติเชิงพรรณนาของข้อมูลตัวเลข
print("\n--- 1.3 Numeric Describe ---")
print(df.describe(include='all').T)

# 4. จำนวนแถวซ้ำทั้งแถว
print("\n--- 1.4 Exact Duplicates ---")
n_dup = df.duplicated().sum()
print(f"Exact duplicate rows: {n_dup}")

# 5. จำนวนค่าที่แตกต่างในคอลัมน์สำคัญ
print("\n--- 1.5 Unique Counts (Key Columns) ---")
key_cols = ['Transaction_ID', 'Customer_ID', 'Customer_Email', 'Gender',
            'Payment_Method', 'Order_Status', 'Is_Promotion', 'Province']
for c in key_cols:
    print(f"{c:20s}: {df[c].nunique()} unique values")

# 6. ตัวอย่างค่าที่พบในคอลัมน์ Categorical ที่มีปัญหา
print("\n--- 1.6 Sample of inconsistent categorical values ---")
print("Gender values:", df['Gender'].unique()[:15])
print("Payment_Method values:", df['Payment_Method'].unique()[:15])
print("Order_Status values:", df['Order_Status'].unique())
print("Order_Date sample formats:", df['Order_Date'].astype(str).str[:10].unique()[:10])

"""### คำถาม 1
ระบุปัญหาที่พบอย่างน้อย **5 ปัญหา** และจับคู่กับมิติ Data Quality อย่างน้อย **3 มิติ**

| ปัญหาที่พบ | คอลัมน์ | มิติ Data Quality | หลักฐาน/จำนวนแถว |
| ปัญหาที่พบ | คอลัมน์ | มิติ Data Quality | หลักฐาน/จำนวนแถว |
|---|---|---|---|
| 1. Missing Values ในอีเมลลูกค้า | `Customer_Email` | **Completeness** | ~45 แถว (~7.5%) |
| 2. Missing Values ในจังหวัด | `Province` | **Completeness** | ~10 แถว |
| 3. รูปแบบ Gender ไม่มาตรฐาน (10+ รูปแบบ) | `Gender` | **Consistency** | ครอบคลุมเกือบทุกแถว |
| 4. Order_Date มี 5+ ฟอร์แมต และค่า garbage (`not_a_date`, `31/02/2026`, `2026-13-05`) | `Order_Date` | **Validity** + **Consistency** | พบ ~3 แถว invalid + หลายร้อยแถว format ต่างกัน |
| 5. Transaction_ID ซ้ำทั้งแถว | ทุกคอลัมน์ | **Uniqueness** | ≥ 15 คู่ |
| 6. Quantity ติดลบ / เกินขอบเขต | `Quantity` | **Validity** | 0, -3, 99 (3 แถว) |
| 7. Transaction_Amount ไม่ตรงสูตร และมีค่าติดลบ | `Transaction_Amount` | **Accuracy** | `-1.0`, `-500.0`, `666666`, `11530.53` |
| 8. Order_Status ไม่อยู่ในชุดมาตรฐาน | `Order_Status` | **Validity** | `unknown_status`, `done`, `Cancel` |
| 9. Load_Delay > 24 ชม. | `Load_Timestamp` | **Timeliness** | หลายสิบแถว (เช่น row 21, 89, 178, 431) |
| 10. Near Duplicate ในชื่อ (`Ploy  Saelim` vs `Ploy Saelim`) | `Customer_Name` | **Uniqueness** | row 98 vs 97/237/348 |

## 2) Completeness: จัดการ Missing Values
"""

# TODO 2.1: ตรวจสอบ Customer_Email และ Province ที่หายไป

# TODO 2.2: ออกแบบวิธีเติม Customer_Email โดยต้องไม่ทำให้แถว Fact หาย
# แนวคิดสำหรับ DW: unknown member / surrogate placeholder และสร้าง flag เพื่อย้อนตรวจสอบได้

# TODO 2.3: เติม Province ที่หายเป็น 'Unknown' พร้อม flag

# TODO 2.1: ตรวจสอบ Customer_Email และ Province ที่หายไป
print("Missing Customer_Email:", df['Customer_Email'].isna().sum())
print("Missing Province:", df['Province'].isna().sum())

# TODO 2.2: เติม Customer_Email ด้วย placeholder ที่ traceable ได้
# สร้าง flag ก่อนเติม (สำคัญมาก — ต้องทำก่อนเติม)
df['Customer_Email_Was_Missing'] = df['Customer_Email'].isna()

# เติมอีเมลด้วย unknown_<Customer_ID>@unknown.local เพื่อให้สืบสวนกลับได้
df['Customer_Email'] = df.apply(
    lambda r: f"unknown_{r['Customer_ID']}@unknown.local"
    if pd.isna(r['Customer_Email']) else r['Customer_Email'],
    axis=1
)

# TODO 2.3: เติม Province เป็น 'Unknown' พร้อม flag
df['Province_Was_Missing'] = df['Province'].isna()
df['Province'] = df['Province'].fillna('Unknown')

print("\nAfter imputation:")
print("Missing Customer_Email:", df['Customer_Email'].isna().sum())
print("Missing Province:", df['Province'].isna().sum())
print("Sample of imputed emails:")
print(df[df['Customer_Email_Was_Missing']]['Customer_Email'].head())

"""### คำถาม 2
อธิบายว่าเหตุใดการใช้ `dropna()` กับ `Customer_Email` อาจทำให้ยอดขายรวมใน Data Warehouse ผิดเพี้ยน และเหตุใดการเติมค่าเฉลี่ยจึงไม่เหมาะกับข้อมูลประเภทอีเมล


การใช้ dropna() กับ Customer_Email ทำให้ยอดขายรวมใน DW ผิดเพี้ยนเพราะ:

แถว Fact (Transaction) ที่มียอด Transaction_Amount จริงจะหายไปประมาณ 7–8% ของปริมาณธุรกรรมทั้งหมด
ในมุม DW, Fact table ต้องเก็ก granular ที่สุด การ drop ทำให้ SUM(Transaction_Amount) ต่ำกว่าความเป็นจริง
ลูกค้าที่ไม่มีอีเมลอาจเป็น guest checkout ซึ่งยังเป็นรายได้จริง การตัดทิ้ง = ตัดรายได้ออกจากรายงาน
ถ้าเป็น dimension สำคัญ (เช่น รายงานยอดขายรายเดือน) จะทำให้ trend ผิดเพี้ยน
การเติมค่าเฉลี่ย (mean imputation) ไม่เหมาะกับอีเมลเพราะ:

อีเมลเป็น Categorical/Nominal data ไม่ใช่ตัวเลข — ไม่มีค่าเฉลี่ยทางคณิตศาสตร์
การเติม "อีเมลที่พบบ่อยที่สุด" (mode) จะทำให้ลูกค้าคนหนึ่งกลายเป็นเจ้าของคำสั่งซื้อของคนอื่น → ผิด Accuracy และ Legal/Privacy (GDPR/PDPA)
อีเมลเป็น PII การเติมค่าสมมติอาจทำให้ส่งอีเมลไปยังบุคคลผิด
วิธีที่ถูกต้องคือสร้าง surrogate key หรือ placeholder ที่ trace ได้ (เช่น unknown_<ID>@unknown.local) และ flag เพื่อให้ audit ภายหลัง

## 3) Consistency: จัดรูปแบบข้อมูลให้เป็นมาตรฐาน
"""

# TODO 3.1: Standardize Gender ให้เหลือ M, F, Unknown

# TODO 3.2: Standardize Payment_Method ให้เหลือ
# Credit Card, PromptPay, Cash on Delivery, Bank Transfer, Unknown

# TODO 3.3: แปลง Order_Date ซึ่งมีหลายรูปแบบให้เป็น YYYY-MM-DD
# ระวังความกำกวมระหว่าง DD/MM/YYYY และ MM/DD/YYYY
# ใช้ Load_Timestamp เป็นข้อมูลประกอบ และสร้าง flag สำหรับค่าที่ต้อง fallback/impute

# TODO 3.1: Standardize Gender -> M, F, Unknown
gender_map = {
    'm': 'M', 'male': 'M', 'MALE': 'M',
    'f': 'F', 'female': 'F', 'FEMALE': 'F',
}
df['Gender'] = (df['Gender'].astype(str).str.strip()
                                  .str.lower()
                                  .map(gender_map)
                                  .fillna('Unknown'))

# TODO 3.2: Standardize Payment_Method
payment_map = {
    'pp': 'PromptPay', 'promptpay': 'PromptPay', 'prompt pay': 'PromptPay',
    'cod': 'Cash on Delivery',
    'transfer': 'Bank Transfer', 'bank_transfer': 'Bank Transfer',
    'cc': 'Credit Card', 'credit card': 'Credit Card', 'card': 'Credit Card',
    'cash': 'Cash on Delivery',
}
df['Payment_Method'] = (df['Payment_Method'].astype(str).str.strip().str.lower()
                                            .map(payment_map)
                                            .fillna('Unknown'))

# TODO 3.3: แปลง Order_Date เป็น YYYY-MM-DD พร้อม flag
df['Order_Date_Original'] = df['Order_Date'].astype(str)
parse_method = []
parsed_dates = []

for orig, load_ts in zip(df['Order_Date_Original'], df['Load_Timestamp']):
    s = str(orig).strip()
    method = 'unknown'
    dt = pd.NaT
    # 1) ISO format YYYY-MM-DD หรือ YYYY/MM/DD
    try:
        dt = pd.to_datetime(s, format='%Y-%m-%d')
        method = 'iso'
    except ValueError:
        pass
    if pd.isna(dt) and '/' in s and s.count('/') == 2:
        parts = s.split('/')
        # รองรับ YYYY/MM/DD
        if len(parts[0]) == 4:
            try:
                dt = pd.to_datetime(s, format='%Y/%m/%d')
                method = 'yyyy_slash'
            except ValueError:
                pass
        else:
            a, b, c = int(parts[0]), int(parts[1]), int(parts[2])
            # ใช้ Load_Timestamp ช่วยตัดสิน: ดูว่าควรเป็น DD/MM หรือ MM/DD
            try:
                load_date = pd.to_datetime(load_ts)
            except:
                load_date = pd.NaT
            # ถ้า a > 12 -> ต้องเป็น DD/MM/YYYY (เพราะเดือนไม่เกิน 12)
            if a > 12 and b <= 12:
                dt = pd.to_datetime(s, format='%d/%m/%Y', errors='coerce')
                method = 'dd_mm_yyyy_inferred'
            elif b > 12 and a <= 12:
                dt = pd.to_datetime(s, format='%m/%d/%Y', errors='coerce')
                method = 'mm_dd_yyyy_inferred'
            else:
                # คำกำกวม: ใช้ Load_Timestamp เป็น anchor
                # สมมติ Load_Timestamp อยู่ใกล้วันสั่งซื้อ (ภายใน 30 วัน) -> เลือก interpretation ที่ใกล้ที่สุด
                try_ddmm = pd.to_datetime(s, format='%d/%m/%Y', errors='coerce')
                try_mmdd = pd.to_datetime(s, format='%m/%d/%Y', errors='coerce')
                if pd.notna(load_date) and pd.notna(try_ddmm) and pd.notna(try_mmdd):
                    diff_ddmm = abs((try_ddmm - load_date).days)
                    diff_mmdd = abs((try_mmdd - load_date).days)
                    if diff_ddmm <= diff_mmdd:
                        dt, method = try_ddmm, 'dd_mm_yyyy_by_load_ts'
                    else:
                        dt, method = try_mmdd, 'mm_dd_yyyy_by_load_ts'
                else:
                    # default ใช้ DD/MM/YYYY (ธุรกิจไทย)
                    dt = pd.to_datetime(s, format='%d/%m/%Y', errors='coerce')
                    method = 'dd_mm_yyyy_default'
    if pd.isna(dt) and '-' in s and s.count('-') == 2:
        parts = s.split('-')
        if len(parts[0]) == 4:
            dt = pd.to_datetime(s, format='%Y-%m-%d', errors='coerce')
            method = 'iso'
        else:
            dt = pd.to_datetime(s, format='%d-%m-%Y', errors='coerce')
            method = 'dd_mm_yyyy_dash'
    if pd.isna(dt):
        # fallback: ใช้ Load_Timestamp
        try:
            dt = pd.to_datetime(load_ts).normalize()
            method = 'fallback_load_ts'
        except:
            method = 'parse_failed'
    parse_method.append(method)
    parsed_dates.append(dt)

df['Order_Date_Parsed'] = parsed_dates
df['Order_Date_Parse_Method'] = parse_method
df['Order_Date_Was_Imputed'] = df['Order_Date_Parse_Method'].isin(
    ['fallback_load_ts', 'parse_failed', 'unknown']
)
df['Order_Date'] = df['Order_Date_Parsed'].dt.strftime('%Y-%m-%d')

print(df['Order_Date_Parse_Method'].value_counts())
print("\nImputed count:", df['Order_Date_Was_Imputed'].sum())

"""### คำถาม 3
ยกตัวอย่าง 1 วันที่สามารถตีความได้ทั้ง DD/MM/YYYY และ MM/DD/YYYY แล้วอธิบายว่าคุณใช้หลักฐานใดช่วยตัดสิน

ตัวอย่าง: 02/04/2026 ใน row 41 (T000250) สามารถตีความเป็น:

DD/MM/YYYY = 2 เมษายน 2026
MM/DD/YYYY = 4 กุมภาพันธ์ 2026

หลักฐานที่ใช้ตัดสิน:

Load_Timestamp = 2026-02-04 19:00:00 → ถ้าเป็น DD/MM (2 เมษา) ระยะห่างจาก Load จะ 62 วัน แต่ถ้าเป็น MM/DD (4 ก.พ.) จะห่างแค่ ~1 ชม. → น่าจะเป็น MM/DD/YYYY แต่ถ้าระบบบันทึกทันทีหลังสั่งซื้อ

ภาษา/ท้องถิ่น: ธุรกิจไทยมักใช้ DD/MM/YYYY → น้ำหนักไปทาง 2 เมษา

Business rule: ถ้า Load_Timestamp ห่างจาก Order_Date มากเกินไป (เช่น > 7 วัน) อาจเป็น batch load ล่าช้า ต้องเลือกแบบที่เป็นไปได้ตาม context

## 4) Uniqueness: ข้อมูลซ้ำและความซ้ำซ้อนเชิงความหมาย
"""

# TODO 4.1: นับและลบ Exact Duplicates โดยเก็บแถวแรก

# TODO 4.2 (Bonus): ตรวจหาลูกค้าที่ Customer_Email เดียวกัน แต่ Customer_Name เขียนต่างกัน
# อธิบายว่าเหตุใด drop_duplicates() เพียงอย่างเดียวจึงตรวจไม่พบ Near Duplicate

# TODO 4.1: นับและลบ Exact Duplicates โดยเก็บแถวแรก
n_before = len(df)
df = df.drop_duplicates(keep='first').reset_index(drop=True)
n_after = len(df)
print(f"Rows before: {n_before}, after: {n_after}, removed: {n_before - n_after}")

# TODO 4.2 (Bonus): Near Duplicate - Customer_Email เดียวกัน แต่ Customer_Name ต่างกัน
email_name_counts = (df.groupby('Customer_Email')['Customer_Name']
                      .nunique().reset_index(name='distinct_names'))
near_dup_emails = email_name_counts[email_name_counts['distinct_names'] > 1]
print(f"\nEmails with multiple distinct names (Near Duplicates): {len(near_dup_emails)}")
print(near_dup_emails.head(10))

# ดูตัวอย่าง Near Duplicate
if len(near_dup_emails) > 0:
    example_email = near_dup_emails.iloc[0]['Customer_Email']
    print(f"\nExample: {example_email}")
    print(df[df['Customer_Email'] == example_email][['Customer_ID', 'Customer_Name']].drop_duplicates())

"""## 5) Accuracy และ Validity: ตรวจสอบกฎธุรกิจ"""

# TODO 5.1: แปลง Quantity, Unit_Price, Discount_Rate และ Transaction_Amount เป็นตัวเลข

# TODO 5.2: ตรวจ Quantity ต้องอยู่ในช่วง 1-20

# TODO 5.3: คำนวณ Expected_Amount = Quantity * Unit_Price * (1 - Discount_Rate)
# สร้าง Accuracy_Flag เมื่อผลต่างเกิน 1 บาท

# TODO 5.4: Standardize Order_Status และตรวจ Validity

# TODO 5.1: แปลงคอลัมน์ตัวเลข
num_cols = ['Quantity', 'Unit_Price', 'Discount_Rate', 'Transaction_Amount']
for c in num_cols:
    df[c] = pd.to_numeric(df[c], errors='coerce')

# TODO 5.2: ตรวจ Quantity ต้องอยู่ในช่วง 1-20
df['Quantity_Was_Invalid'] = ~df['Quantity'].between(1, 20)
print(f"Invalid Quantity rows: {df['Quantity_Was_Invalid'].sum()}")
print(df[df['Quantity_Was_Invalid']][['Transaction_ID','Quantity','Transaction_Amount']])

# TODO 5.3: คำนวณ Expected_Amount และ Accuracy_Flag
df['Expected_Amount'] = df['Quantity'] * df['Unit_Price'] * (1 - df['Discount_Rate'])
df['Amount_Diff'] = (df['Transaction_Amount'] - df['Expected_Amount']).abs()
df['Accuracy_Flag'] = df['Amount_Diff'] > 1.0
print(f"\nMismatched amounts (>1 THB diff): {df['Accuracy_Flag'].sum()}")

# TODO 5.4: Standardize Order_Status
status_map = {
    'cancelled': 'Cancelled', 'cancel': 'Cancelled',
    'completed': 'Completed', 'done': 'Completed',
    'processing': 'Processing',
    'returned': 'Returned',
}
df['Order_Status_Original'] = df['Order_Status']
df['Order_Status'] = (df['Order_Status'].astype(str).str.strip().str.lower()
                      .map(status_map).fillna('Unknown'))
df['Status_Was_Invalid'] = df['Order_Status'] == 'Unknown'
print(f"\nInvalid status count: {df['Status_Was_Invalid'].sum()}")
print(df['Order_Status'].value_counts())

"""### คำถาม 4
รายการที่ `Transaction_Amount` ไม่ตรงกับสูตรควรแก้ไขทุกแถวหรือไม่? ให้อธิบายผลของ `Is_Promotion` ต่อการตัดสินใจ

ไม่ควรแก้ทุกแถวอัตโนมัติ เพราะ:

รายการ Is_Promotion = 'Y' อาจมีส่วนลดเพิ่มเติมที่ไม่ได้สะท้อนใน Discount_Rate เช่น:
ส่วนลด coupon, voucher, ส่วนลดสมาชิก
ของแถม, ราคาพิเศษ flash sale
บางรายการมียอด > สูตร เช่น row 60 (1227.8 แต่ Expected = 122.78) แสดงว่ามี shipping fee หรือ markup เพิ่ม

ตัวอย่างเช่น row 60: Quantity=1, Unit_Price=144.45, Discount=0.15, Expected=122.78 แต่ Transaction_Amount=1227.8 → ผลต่าง ~1,105 บาท ถ้า Is_Promotion=Y → น่าจะเป็น shipping+handling หรือสินค้า bundle

ควรทำ:
สร้าง Accuracy_Flag แต่ไม่ overwrite Transaction_Amount
แยกยอด Promotion ออกจาก Normal ใน report
ส่ง flag ให้ business team ตรวจสอบ
เก็บ audit log: Original_Amount vs Expected_Amount

Is_Promotion เปลี่ยนการตัดสินใจ โดยเป็นตัวบอกว่า "ยอดไม่ตรงสูตรเป็นเรื่องปกติของโปรโมชัน" ไม่ใช่ error

## 6) Outliers: IQR และ Capping/Clipping
"""

# TODO 6.1: ใช้เฉพาะรายการที่ Is_Promotion != 'Y' คำนวณ Q1, Q3, IQR, Lower Bound, Upper Bound

# TODO 6.2: สร้าง Outlier Flag ก่อนทำ Capping

# TODO 6.3: ใช้ .clip() กับ Transaction_Amount เฉพาะรายการที่ไม่ใช่โปรโมชัน

# TODO 6.4: วาด Boxplot ก่อนและหลัง Capping

# TODO 6.1: คำนวณ IQR จาก non-promotion เท่านั้น
non_promo = df[df['Is_Promotion'] != 'Y']['Transaction_Amount']
Q1 = non_promo.quantile(0.25)
Q3 = non_promo.quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
print(f"Q1={Q1:.2f}, Q3={Q3:.2f}, IQR={IQR:.2f}")
print(f"Lower={lower:.2f}, Upper={upper:.2f}")

# TODO 6.2: Outlier flag ก่อน capping (ทุกแถว)
df['Outlier_Flag_Before_Capping'] = (
    (df['Transaction_Amount'] < lower) | (df['Transaction_Amount'] > upper)
)
print(f"\nOutliers detected: {df['Outlier_Flag_Before_Capping'].sum()}")

# TODO 6.3: Capping เฉพาะ non-promotion
mask_non_promo = df['Is_Promotion'] != 'Y'
df.loc[mask_non_promo, 'Transaction_Amount_Capped'] = (
    df.loc[mask_non_promo, 'Transaction_Amount'].clip(lower=lower, upper=upper)
)
df.loc[~mask_non_promo, 'Transaction_Amount_Capped'] = df.loc[~mask_non_promo, 'Transaction_Amount']
df['Transaction_Amount_Original'] = df['Transaction_Amount']
df['Transaction_Amount'] = df['Transaction_Amount_Capped']

# TODO 6.4: Boxplot ก่อน/หลัง
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].boxplot(df['Transaction_Amount_Original'].dropna())
axes[0].set_title('Before Capping (with outliers like 999999)')
axes[0].set_ylabel('Transaction_Amount')
axes[1].boxplot(df['Transaction_Amount'].dropna())
axes[1].set_title('After Capping (non-promo only)')
plt.tight_layout()
plt.savefig(OUTPUT_DIR / 'boxplot_before_after.png', dpi=100, bbox_inches='tight')
plt.show()

"""### คำถาม 5
เพราะเหตุใดข้อมูลที่อยู่นอก IQR Bound จึงไม่จำเป็นต้องเป็นข้อมูลผิดเสมอ? ยกตัวอย่างจาก Dataset นี้

Outlier ตาม IQR เป็นเพียง statistical signal ไม่ใช่ business error เสมอ เพราะ:

รายการ Promotion (Is_Promotion='Y') อาจมียอดสูงผิดปกติแต่เป็นธุรกรรมจริง เช่น:
row 367: T000406 ยอด 19,610.76 (น่าจะเป็น bulk order ใน flash sale)
row 185: T000282 ยอด 11,530.53 (น่าจะเป็น high-value promotion)
row 230: T000584 ยอด 7,323.84
row 593: T000159 ยอด 6,943.20
ทั้งหมดนี้มี Is_Promotion='Y' ซึ่งอาจเป็นยอดจริง
High-value customers บางรายการสั่งจำนวนมาก (Quantity=6, Unit_Price สูง) → Expected_Amount ปกติแต่ตกเป็น outlier ใน statistical sense
ค่า 666666, 777777, 888888, 999999 — เหล่านี้เป็น placeholder/error code ของระบบ (ดูจากรูปแบบตัวเลขซ้ำ) → ควรส่งให้ engineering ตรวจสอบไม่ใช่ capping ทิ้ง
Capping ทำลาย insight: ถ้า cap ทิ้งหมด จะไม่เห็นว่ามี bulk buyer ที่อาจเป็น B2B customer สำคัญ

## 7) Timeliness: ความทันเวลาในการโหลดข้อมูล
"""

# TODO 7: คำนวณ Load_Delay_Hours จาก Order_Date ถึง Load_Timestamp
# กำหนด Late เมื่อมากกว่า 24 ชั่วโมง และสรุปจำนวน/ร้อยละ

# TODO 7: คำนวณ Load_Delay_Hours
df['Order_Date_Parsed'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df['Load_Timestamp_Parsed'] = pd.to_datetime(df['Load_Timestamp'], errors='coerce')
df['Load_Delay_Hours'] = (
    (df['Load_Timestamp_Parsed'] - df['Order_Date_Parsed']).dt.total_seconds() / 3600
)
df['Is_Late_Load'] = df['Load_Delay_Hours'] > 24

n_late = df['Is_Late_Load'].sum()
pct_late = (n_late / len(df) * 100).round(2)
print(f"Late loads (>24h): {n_late} rows ({pct_late}%)")
print("\nTop 5 latest loads:")
print(df.nlargest(5, 'Load_Delay_Hours')[
    ['Transaction_ID','Order_Date','Load_Timestamp','Load_Delay_Hours','Is_Promotion']
])

"""## 8) Data Quality Report และ Export"""

# TODO 8.1: สรุปตัวชี้วัดก่อนและหลัง Cleaning เป็น DataFrame
# อย่างน้อย: rows, missing email, exact duplicates, invalid dates, mismatched amounts,
# outliers capped, late loads และ invalid statuses

# TODO 8.2: Export
# df.to_csv(OUTPUT_DIR / 'e_commerce_clean.csv', index=False, encoding='utf-8-sig')
# report.to_csv(OUTPUT_DIR / 'data_quality_report.csv', index=False, encoding='utf-8-sig')

# TODO 8.1: สรุปตัวชี้วัดก่อน-หลัง Cleaning
report = pd.DataFrame({
    'Metric': [
        'Total Rows',
        'Missing Customer_Email (before)',
        'Missing Customer_Email (after)',
        'Missing Province (before)',
        'Missing Province (after)',
        'Exact Duplicates (before)',
        'Exact Duplicates (after)',
        'Invalid Order_Date (not_a_date/parse_failed)',
        'Order_Date Imputed',
        'Invalid Quantity (out of 1-20)',
        'Mismatched Amounts (>1 THB diff)',
        'Invalid Order_Status',
        'Outliers Detected (IQR)',
        'Outliers Capped (non-promo only)',
        'Late Loads (>24h)',
        'Promotion Rows Preserved',
    ],
    'Before': [
        len(df_raw), df_raw['Customer_Email'].isna().sum(), 0,
        df_raw['Province'].isna().sum(), 0,
        df_raw.duplicated().sum(), 0,
        df_raw['Order_Date'].astype(str).isin(['not_a_date']).sum(),
        df['Order_Date_Was_Imputed'].sum(),
        df['Quantity_Was_Invalid'].sum(),
        df['Accuracy_Flag'].sum(),
        df['Status_Was_Invalid'].sum(),
        df['Outlier_Flag_Before_Capping'].sum(),
        ((df['Is_Promotion'] != 'Y') & df['Outlier_Flag_Before_Capping']).sum(),
        df['Is_Late_Load'].sum(),
        (df['Is_Promotion'] == 'Y').sum(),
    ],
    'After': [
        len(df), 0, 0,
        0, 0,
        0, 0,
        0, 0,
        df['Quantity_Was_Invalid'].sum(),  # flagged but not auto-corrected
        df['Accuracy_Flag'].sum(),          # flagged
        df['Status_Was_Invalid'].sum(),
        0,  # capped - flag preserved
        0,  # capped
        df['Is_Late_Load'].sum(),
        (df['Is_Promotion'] == 'Y').sum(),
    ]
})
print(report)

# TODO 8.2: Export
df.to_csv(OUTPUT_DIR / 'e_commerce_clean.csv', index=False, encoding='utf-8-sig')
report.to_csv(OUTPUT_DIR / 'data_quality_report.csv', index=False, encoding='utf-8-sig')
print("\n✅ Exported:")
print(" - e_commerce_clean.csv")
print(" - data_quality_report.csv")

"""## 9) Reflection
ตอบเป็นย่อหน้าสั้น ๆ
1. ขั้นตอนใดมีความเสี่ยงทำให้ข้อมูลจริงสูญหายมากที่สุด?
การลบ Exact Duplicates ด้วย drop_duplicates(keep='first') มีความเสี่ยงสูงสุดเพราะ:

ถ้าระบบ source มี Load_Timestamp หรือ batch ID ต่างกัน แต่เรา drop ทั้งหมด อาจเสียประวัติการแก้ไข

ถ้า duplicate เกิดจาก "สั่งซื้อซ้ำจริง ๆ" (ไม่ใช่ error) การ drop จะทำให้ยอดขายหาย

ควรเก็บ audit table ของ rows ที่ถูก drop และตรวจสอบว่า Transaction_ID เดียวกันมี attributes ต่างกันก่อน drop

รองลงมาคือ Capping ที่เขียนทับ Transaction_Amount เดิม — ต้องเก็บ _Original column เสมอ


2. กฎใดควรนำไปทำ Automation ใน Data Pipeline?
กฎที่ deterministic และ low-risk ควร automate:

Standardization ของ Gender, Payment_Method, Order_Status (mapping table)

Parsing Order_Date ด้วย multi-format + fallback rule

Missing value imputation สำหรับ Customer_Email (placeholder pattern)

IQR Capping สำหรับ non-promotion (รักษา promotion)

Computing Expected_Amount + Accuracy_Flag (deterministic)


กฎที่ ไม่ควร automate:

การ drop rows ที่ mismatched amount ใน promotion

การแก้ Quantity ที่ invalid → ควร flag แล้วส่งให้ business ตรวจ

3. หากใช้ Great Expectations คุณจะสร้าง Expectation ใดอย่างน้อย 3 ข้อ?

# 1) ไม่มี null ในคอลัมน์ fact ที่สำคัญ
expect_column_values_to_not_be_null(column='Transaction_ID')
expect_column_values_to_not_be_null(column='Customer_ID')

# 2) Quantity อยู่ในช่วงที่กำหนด
expect_column_values_to_be_between(
    column='Quantity', min_value=1, max_value=20,
    mostly=0.95  # อนุญาต 5% exception
)

# 3) Transaction_Amount ไม่ติดลบ (ยกเว้น refund ที่ flag)
expect_column_values_to_be_between(
    column='Transaction_Amount', min_value=0, max_value=100000
)

# 4) Order_Status อยู่ในชุดที่กำหนด
expect_column_values_to_be_in_set(
    column='Order_Status',
    value_set=['Completed','Processing','Cancelled','Returned','Unknown']
)

# 5) Customer_Email มีรูปแบบที่ถูกต้อง
expect_column_values_to_match_regex(
    column='Customer_Email',
    regex=r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
)

## Checklist ก่อนส่ง
- [ ] Notebook รันจากบนลงล่างได้โดยไม่ Error
- [ ] มีคำตอบคำถามทั้ง 5 ข้อและ Reflection
- [ ] ส่ง `e_commerce_clean.csv`
- [ ] ส่ง `data_quality_report.csv`
- [ ] ไม่ลบรายการโปรโมชันเพียงเพราะเป็น Outlier
"""